trigger:
- master

jobs:
- job: Xcode_test
  strategy:
    maxParallel: 10
    matrix:
      ios14:
        IMAGE_NAME: 'macos-10.15'
        XCODE_DEVELOPER_PATH: /Applications/Xcode_12.4.app
        IOS_SIMULATORS: 'iPhone 11,OS=14.3'
  pool:
    vmImage: $(IMAGE_NAME)
  steps:
  - script: xcodebuild -scheme TIM -sdk iphonesimulator -destination 'platform=iOS Simulator,name=$(IOS_SIMULATORS)' test
    displayName: 'xcodebuild test'
