trigger:
- master

jobs:
- job: Xcode_test
  strategy:
    maxParallel: 10
    matrix:
      # Previous iOS versions requires previous Xcode verisons, which isn't supported by TIM
      ios14:
        IMAGE_NAME: 'macos-10.15'
        XCODE_DEVELOPER_PATH: /Applications/Xcode_12.4.app
        IOS_SIMULATORS: 'iPhone 11,OS=14.4'
  pool:
    vmImage: $(IMAGE_NAME)
  steps:
  - script: sudo xcode-select -switch $(XCODE_DEVELOPER_PATH)
    displayName: Select Xcode version
  
  - script: xcodebuild -version
    displayName: Xcode version
    
  - script: xcodebuild -scheme TIM -sdk iphonesimulator -destination 'platform=iOS Simulator,name=$(IOS_SIMULATORS)' test
    displayName: 'xcodebuild test'
